# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - run: npm ci
    - run: npm run lint
    - run: npm run build
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.areksiekierski.pl
        username: areks75
        password: ${{ secrets.FTP_PASS }}
        port: 21
        local-dir: dist/
        server-dir: domains/areksiekierski.pl/public_html
